In [7]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn import svm
from read_files import X,y
from read_files import USERCODE_X
from utils import tokenize_tweet
import numpy as np
import regex as re
from io import StringIO
from sklearn.model_selection import train_test_split, KFold
from tqdm import tqdm
from nltk.tokenize import TweetTokenizer 
from sklearn.metrics import accuracy_score, f1_score

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [9]:
#collecting all text for all authors 

def collect(array):

    train_author = [None for i in range(array.shape[0])]

    for i, author in enumerate(array):
        buf = StringIO()
        for tweet in author:
            buf.write(tweet + "")
        single_text = buf.getvalue()
        train_author[i] = single_text

    train_author = np.array(train_author)
    return train_author 


In [4]:
#counting bigrams 
tknzr = TweetTokenizer()
vectorizer = CountVectorizer(analyzer='word', tokenizer = tknzr.tokenize, ngram_range=(2, 2))
X_train_f = vectorizer.fit_transform(collect(X_train))

In [5]:
X_test_f = vectorizer.transform(collect(X_test))

In [8]:
clf = svm.SVC()
clf.fit(X_train_f, y_train)

SVC()

In [9]:
#word accuracy
accuracy_score(y_test, clf.predict(X_test_f))

0.7380952380952381

In [29]:
kf = KFold(n_splits=7)
result_dict = []
for i, (train_index, test_index) in tqdm(enumerate(kf.split(X_train))):
    vectorizer = CountVectorizer(analyzer='char', ngram_range=(5, 5)
    cross_train = X_train[train_index]
    cross_test = X_train[test_index]
    label_train = y_train[train_index]
    label_test = y_train[test_index]
    X_train_f = vectorizer.fit_transform(collect(cross_train))
    X_test_f = vectorizer.transform(collect(cross_test))
    clf = svm.SVC()
    clf.fit(X_train_f, label_train)
    result_dict.append((accuracy_score(label_train, clf.predict(X_train_f)),accuracy_score(label_test, clf.predict(X_test_f)), f1_score(label_test, clf.predict(X_test_f), average='weighted')))

7it [01:57, 16.76s/it]


In [25]:
# 5-Char
np.array(result_dict).mean(axis=0)

array([0.88888889, 0.82653061, 0.82698918])

In [ ]:
kf = KFold(n_splits=7)
result_dict = []
for i, (train_index, test_index) in tqdm(enumerate(kf.split(X_train))):
    vectorizer = CountVectorizer(analyzer='char', ngram_range=(4, 4)
    cross_train = X_train[train_index]
    cross_test = X_train[test_index]
    label_train = y_train[train_index]
    label_test = y_train[test_index]
    X_train_f = vectorizer.fit_transform(collect(cross_train))
    X_test_f = vectorizer.transform(collect(cross_test))
    clf = svm.SVC()
    clf.fit(X_train_f, label_train)
    result_dict.append((accuracy_score(label_train, clf.predict(X_train_f)),accuracy_score(label_test, clf.predict(X_test_f)), f1_score(label_test, clf.predict(X_test_f), average='weighted')))

In [28]:
# 4-Char
np.array(result_dict).mean(axis=0)

array([0.87244898, 0.84353741, 0.84362666])

In [ ]:
kf = KFold(n_splits=7)
result_dict = []
for i, (train_index, test_index) in tqdm(enumerate(kf.split(X_train))):
    vectorizer = CountVectorizer(analyzer='char', ngram_range=(3, 3)
    cross_train = X_train[train_index]
    cross_test = X_train[test_index]
    label_train = y_train[train_index]
    label_test = y_train[test_index]
    X_train_f = vectorizer.fit_transform(collect(cross_train))
    X_test_f = vectorizer.transform(collect(cross_test))
    clf = svm.SVC()
    clf.fit(X_train_f, label_train)
    result_dict.append((accuracy_score(label_train, clf.predict(X_train_f)),accuracy_score(label_test, clf.predict(X_test_f)), f1_score(label_test, clf.predict(X_test_f), average='weighted')))

In [30]:
# 3-Char
np.array(result_dict).mean(axis=0)

array([0.87244898, 0.83673469, 0.83600361])

In [33]:
kf = KFold(n_splits=7)
result_dict = []
for i, (train_index, test_index) in tqdm(enumerate(kf.split(X_train))):
    vectorizer = CountVectorizer(analyzer='char', ngram_range=(2, 2))
    cross_train = X_train[train_index]
    cross_test = X_train[test_index]
    label_train = y_train[train_index]
    label_test = y_train[test_index]
    X_train_f = vectorizer.fit_transform(collect(cross_train))
    X_test_f = vectorizer.transform(collect(cross_test))
    clf = svm.SVC()
    clf.fit(X_train_f, label_train)
    result_dict.append((accuracy_score(label_train, clf.predict(X_train_f)),accuracy_score(label_test, clf.predict(X_test_f)), f1_score(label_test, clf.predict(X_test_f), average='weighted')))

7it [01:47, 15.35s/it]


In [34]:
# Bi-Char
np.array(result_dict).mean(axis=0)

array([0.85090703, 0.82653061, 0.8239249 ])

In [35]:
vectorizer = CountVectorizer(analyzer='char', ngram_range=(4, 4))
X_train_f = vectorizer.fit_transform(collect(X_train))
X_test_f = vectorizer.transform(collect(X_test))

In [36]:
#char accuracy
clf = svm.SVC()
clf.fit(X_train_f, y_train)
accuracy_score(y_test, clf.predict(X_test_f))

0.8492063492063492

In [37]:
f1_score(y_test, clf.predict(X_test_f), average="weighted")

0.8496359607470719

In [ ]:
0.83333

In [17]:
print(type(X_train_f))

from sklearn.decomposition import PCA

pca = PCA(n_components=10)
pca.fit(X_train_f.toarray())

<class 'scipy.sparse.csr.csr_matrix'>


PCA(n_components=10)

In [18]:
print(pca.explained_variance_ratio_)

[0.45295345 0.20643717 0.13691326 0.03973111 0.01404132 0.01236087
 0.01044976 0.00860926 0.00760826 0.00658638]


In [22]:
clf = svm.SVC(probability=  True)
clf.fit(pca.transform(X_train_f.toarray()), y_train)
#accuracy_score(y_test, ))

SVC(probability=True)

In [23]:
clf.predict_proba(pca.transform(X_test_f.toarray()))

array([[0.37484311, 0.62515689],
       [0.52446532, 0.47553468],
       [0.99428864, 0.00571136],
       [0.18044511, 0.81955489],
       [0.0819303 , 0.9180697 ],
       [0.78794548, 0.21205452],
       [0.24590154, 0.75409846],
       [0.87969818, 0.12030182],
       [0.97850421, 0.02149579],
       [0.98968573, 0.01031427],
       [0.2256982 , 0.7743018 ],
       [0.79020658, 0.20979342],
       [0.79499108, 0.20500892],
       [0.98983224, 0.01016776],
       [0.97839503, 0.02160497],
       [0.55845308, 0.44154692],
       [0.93513248, 0.06486752],
       [0.04535589, 0.95464411],
       [0.16374774, 0.83625226],
       [0.15087133, 0.84912867],
       [0.68349526, 0.31650474],
       [0.98515475, 0.01484525],
       [0.25709595, 0.74290405],
       [0.82896203, 0.17103797],
       [0.81576148, 0.18423852],
       [0.66740548, 0.33259452],
       [0.88586802, 0.11413198],
       [0.0485514 , 0.9514486 ],
       [0.24939075, 0.75060925],
       [0.20023012, 0.79976988],
       [0.

### Comparing models

In [24]:
X_train, X_test, y_train, y_test = train_test_split(X,y, random_state= 0)

In [25]:
## BASELINE BIGRAM MODEL 

vectorizer = CountVectorizer(analyzer='char', ngram_range=(2, 2))
X_train_f = vectorizer.fit_transform(collect(X_train))
X_test_f = vectorizer.transform(collect(X_test))

In [43]:
clf = svm.SVC(probability = True)
clf.fit(X_train_f, y_train)
baseline_pred_proba = clf.predict_proba(X_test_f)
baseline_pred_proba = clf.predict_proba


In [49]:
clf = svm.SVC(probability = False)
clf.fit(X_train_f, y_train)
baseline_pred = clf.predict(X_test_f)



In [32]:
## OUR MODEL

from classifier_methods import *

X_train_F, emoji_pca, profanity_pca, word_pca, emoji_tfidf, profanity_tfidf, words_tfidf = get_features_train(X_train)
X_test_F = get_features_test(X_test, emoji_pca, profanity_pca, word_pca, emoji_tfidf, profanity_tfidf, words_tfidf)





Generating Train Features
Processing features: pos_counts


100%|██████████| 315/315 [00:57<00:00,  5.48it/s]


Individual Predict Processing for features: pos_counts, is complete!
Processing features: author_style_counts


100%|██████████| 315/315 [00:14<00:00, 21.32it/s]


Individual Predict Processing for features: author_style_counts, is complete!
Processing features: lix_score


 64%|██████▍   | 203/315 [00:04<00:02, 49.63it/s]

[]
0


100%|██████████| 315/315 [00:06<00:00, 48.56it/s]


Individual Predict Processing for features: lix_score, is complete!
Processing features: get_sent_polarity


100%|██████████| 315/315 [00:16<00:00, 18.91it/s]


Individual Predict Processing for features: get_sent_polarity, is complete!
Processing features: seperated_punctuation


100%|██████████| 315/315 [00:00<00:00, 417.22it/s]


Individual Predict Processing for features: seperated_punctuation, is complete!
Processing features: tf_idf


100%|██████████| 315/315 [00:06<00:00, 49.00it/s]


Emoji TF_IDF Processing for features: tf_idf, is complete!
Processing features: tf_idf


100%|██████████| 315/315 [00:06<00:00, 45.20it/s]


Profanity TF_IDF Processing for features: tf_idf, is complete!
Processing features: tf_idf


100%|██████████| 315/315 [00:17<00:00, 17.70it/s]


Words TF_IDF Processing for features: tf_idf, is complete!
Generating Test Features
Processing features: pos_counts


100%|██████████| 105/105 [00:19<00:00,  5.28it/s]


Individual Predict Processing for features: pos_counts, is complete!
Processing features: author_style_counts


100%|██████████| 105/105 [00:05<00:00, 20.32it/s]


Individual Predict Processing for features: author_style_counts, is complete!
Processing features: lix_score


100%|██████████| 105/105 [00:02<00:00, 47.31it/s]


Individual Predict Processing for features: lix_score, is complete!
Processing features: get_sent_polarity


100%|██████████| 105/105 [00:05<00:00, 18.65it/s]


Individual Predict Processing for features: get_sent_polarity, is complete!
Processing features: seperated_punctuation


100%|██████████| 105/105 [00:00<00:00, 447.76it/s]


Individual Predict Processing for features: seperated_punctuation, is complete!
Processing features: tf_idf


100%|██████████| 105/105 [00:02<00:00, 47.90it/s]


Individual Predict Processing for features: tf_idf, is complete!
Processing features: tf_idf


100%|██████████| 105/105 [00:02<00:00, 44.33it/s]


Individual Predict Processing for features: tf_idf, is complete!
Processing features: tf_idf


100%|██████████| 105/105 [00:05<00:00, 17.80it/s]

Words TF_IDF Processing for features: tf_idf, is complete!


In [36]:
classifier = RandomForestClassifier()
classifier.fit(X_train_F, y_train)

RandomForestClassifier()

In [42]:
model_pred_proba = classifier.predict_proba(X_test_F)
model_pred = classifier.predict(X_test_F)

In [59]:
file = open('proba_results.txt', 'w', encoding = 'utf-8')

for i in range(len(y_test)):
    file.write(f"{baseline_pred_proba[i][0]}, {baseline_pred_proba[i][1]},  {model_pred_proba[i][0]}, {model_pred_proba[i][1]}\n")


### ML Perceptron 

In [67]:
from sklearn.neural_network import MLPClassifier
from sklearn.datasets import make_classification

y = y_test
X = np.loadtxt('proba_results.txt', delimiter = ',')

In [69]:
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y,random_state=1)

In [72]:
clf = MLPClassifier(random_state=1, max_iter=1000).fit(X_train, y_train)

In [73]:
clf.score(X_test, y_test)

0.8888888888888888

In [1]:
from baseline import baseline_svm
from read_files import X,y

baseline_svm(X,y)

Load XML files complete, number of tweet profiles:  420
Tokenizing and vectorizing input...
Initializing K-fold splits...
Split 0 Accuracy: 0.8333333333333334
Split 0 Accuracy: 0.8809523809523809
Split 0 Accuracy: 0.8690476190476191
Split 0 Accuracy: 0.7976190476190477
Split 0 Accuracy: 0.8333333333333334


UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U3'), dtype('<U3')) -> dtype('<U3')

In [6]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn import svm
from read_files import X,y
from read_files import USERCODE_X
from utils import tokenize_tweet
import numpy as np
import regex as re
from io import StringIO
from sklearn.model_selection import train_test_split
from nltk.tokenize import TweetTokenizer 
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold


def collect(array):

    train_author = [None for i in range(array.shape[0])]

    for i, author in enumerate(array):
        buf = StringIO()
        for tweet in author:
            buf.write(tweet + "")
        single_text = buf.getvalue()
        train_author[i] = single_text

    train_author = np.array(train_author)
    return train_author 

def baseline_svm(data, labels, tokenize = 'char', kfold = 5):

    print("Tokenizing and vectorizing input...")

    if tokenize == 'word':
        tknzr = TweetTokenizer()
        vectorizer = CountVectorizer(analyzer='word', tokenizer = tknzr.tokenize, ngram_range=(2, 2))
        X = vectorizer.fit_transform(collect(data))
    else:
        vectorizer = CountVectorizer(analyzer='char', ngram_range=(2, 2))
        X = vectorizer.fit_transform(collect(data))

    accuracies = []

    print("Initializing K-fold splits...")

    i= 0
    kf = KFold(n_splits=5)
    for train_index, test_index in kf.split(X):
        X_train, X_test = X[train_index], X[test_index]
        y_train, y_test = y[train_index], y[test_index]

        clf = svm.SVC()
        clf.fit(X_train, y_train)
        prediction = clf.predict(X_test)
        print(f"Split {i} Accuracy: {accuracy_score(y_test, prediction)}")
        accuracies.append(accuracy_score(y_test, prediction))
        i+= 1

    print("Average accuracy:", sum(accuracies)/kfold)








In [7]:
baseline_svm(X,y)

Tokenizing and vectorizing input...
Initializing K-fold splits...
Split 0 Accuracy: 0.8333333333333334
Split 1 Accuracy: 0.8809523809523809
Split 2 Accuracy: 0.8690476190476191
Split 3 Accuracy: 0.7976190476190477
Split 4 Accuracy: 0.8333333333333334
<class 'list'> <class 'numpy.float64'>
Average accuracy: 0.8428571428571429
